#!/bin/bash
echo ""
echo "  +—————————————————————————————————————————+"
echo "  |                                         |"
echo "  |     Welcome to ST-Tool Version 0.1      |"
echo "  |                                         |"
echo "  +—————————————————————————————————————————+"
echo ""

if [[ -z $2 ]] 
then
  echo -e "===== Usage: \n   >> stt [function] [config file]."
  exit 1
fi
if [ $1 == "mapmatching" ]
then
  echo "===== Start map matching"
  echo " ---- Read config file from $2"
  command python helper/parse_mmconfig.py $2
  command bash submit_mm_job.tmp
  command rm submit_mm_job.tmp

elif [ $1 == "rangequery" ]
then
    echo "===== Start rangequery on road network"
    command python helper/parse_rqconfig.py $2
    command bash submit_rq_job.tmp
    command rm submit_rq_job.tmp
    
elif [ $1 == "odquery" ]
then 
  echo "===== Start OD query on road network"
  command python helper/parse_odconfig.py $2
  command bash submit_od_job.tmp
  command rm submit_od_job.tmp

elif [ $1 == "speedquery" ]
then 
  echo "===== Start speed query on road network"
  command python helper/parse_speedconfig,py $2
  command bash submit_speed_job.tmp
  command rm submit_speed_job.tmp

else
  echo "===== Function not supported. Please select from { mapmatching, rangequery, odquery, speedquery }"
  exit 1
fi
